language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: K6tYJXJHIFmfgnOHmu3uZj8EPFnRXWwtRX7XPiljPsUulrwuwT1G0xhbcyTVRH5nQaqfA6THUZ8EedrIyY/sNXtEdfdS3MnAV1kwvDo+MtVwerwKScdpGGaPr7GOU+wbIpkVGHlwacT9tqr8xQLmfYc8hIpLZI85cXLkGiDY+a+09/IVWinIud67tLU3+m8yC1m7LMvKaPAcvJQq25OxaHls/ZjmVT4rlKOe+NBkOh2OX0qPhe7xDTh0l3zJZywaL0Svf/58SNUyBRRvBdz2Jhlr3AWnclmpFMUzJxoXZ5V3j3fxX8u/sG0RDbV6aPHML/hhsopepRfg/h9yMqKlc1UzuZO7Sjy8Tt0+XOUmjmRMVr2VadNl/sVyGCXvbcWeAycYPmp1rWdUfDrUWz+uFypQey5NfXrDQP+VWCHZdew5a/EB3XO+Tj8OrpWyHs66PVl+hF8huCVg3Qn5iE8q4W3h+TwCj2AvXDxjGgoQcGVxvEaR1uVkM4bPyCZTM5vAdQ+lKpcik/VCeZqYEb6iW9QESdCYmrNYgR903QzpCqbe7zDS5Xi69ZK0wZ3UkwW+YeOXRPC5qGS6aQAVIDB1qWdgGEFpoEKXEx0ZwC34Ii+++k+9xSYLaUWs5pxwb9/439mnEvRHyMdfF32u4jHpKn9IC/0TamFa9XVXqboxUI0=
  app: rens-demo
  on:
    branch: master
