language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-west-1"
  app: "demo.zp25"
  env: "Demozp25-env"
  bucket_name: "elasticbeanstalk-us-west-1-633956617217"
on:
  branch: master
