language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: v1uA/zi30GlutYLWM/NHfLGz5SVv2k7e4HmrRC5v9g32ch4+CXMUPro6SSJYREZK1NcQdppQ6JWhzkZB8GMSgffUwO4/3CkVTVwGScJfilpLeKMa9v5kKtRVKWvf9DvVlGD8YhQbT4yjR+YSiYAJVyEBQtN1BQ8jLYdNQ4INW3+dRanMqIPxrtK9i1tEbznGHtQVQYmByN9ZeuUsJq/LKUGq1sfca0Q1jg5hlXyTmg3mF1jb/mMldRoFDPwnu6T2LyI3FAaSECTydRxhHsujjJY08pJUla6l+RVZX99GWOoSkPdM6YKmyndECwd6QOhayGENXlEM2YiQuWH48NmVH+8lpZqf83siwYw2ieFNZg0tD3NE6M2quDVDHfXBgWefQzyLTwqpe8pWvFtNFUlbs6U9lfZeHv07whWmmZZjwg//H9iiUJG9aBk7HLogjQsXAuoBT5E6IGcUDZt0LDdKPsxaSiMifkDHDjhzTj2rFW1/1M75CUa3ZI3AWTN1d5fyXvUY4cv9j0qgM7/WAntnNBHtrQN1aIa/nIe2IrSH3QiU05KAuKe9WN6bJAIClxlbRwEXTRlvXdfrbbdiTBIb/C+m29mdSb2GQ1uTDiI3ef2wx+XU+Ki38WW9JGd331/DXr9kEQQ3/BwU5R/+v89JDurSAW+jqFOv2ND7oCnPscY=
  app: rens-demo
  on:
    branch: master
